$(document).ready(function(){
   $('#btn').click(function(){
        $('p').slideUp();
   })
   $('#show').click(function(){
    $('p').slideDown();
    })
    $('#toggle').click(function(){
        $('p').slideToggle();
    })
})